# Generated by Django 4.1.2 on 2022-11-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='sede',
            name='type_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_sede', to='location.type_sede'),
        ),
    ]
