# Generated by Django 4.1.2 on 2022-10-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=15)),
                ('business', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('type_sede', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=15, null=True)),
                ('hostname', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('MAC_address', models.CharField(blank=True, max_length=15, null=True)),
                ('SN', models.CharField(blank=True, max_length=15, null=True)),
                ('brand', models.CharField(blank=True, max_length=15, null=True)),
                ('model', models.CharField(blank=True, max_length=15, null=True)),
                ('type_device', models.CharField(blank=True, max_length=15, null=True)),
                ('subtype_device', models.CharField(blank=True, max_length=15, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=15, null=True)),
                ('power_supply_redundancy', models.BooleanField()),
                ('os', models.CharField(blank=True, max_length=15, null=True)),
                ('version', models.CharField(blank=True, max_length=15, null=True)),
                ('date_update_os', models.DateField()),
                ('telnet', models.BooleanField()),
                ('ssh', models.BooleanField()),
                ('http', models.BooleanField()),
                ('https', models.BooleanField()),
                ('prtg', models.BooleanField()),
                ('orion', models.BooleanField()),
                ('icmp', models.BooleanField()),
                ('snmp', models.CharField(blank=True, max_length=15, null=True)),
                ('snmp_comunity', models.CharField(blank=True, max_length=15, null=True)),
                ('date_install', models.DateField()),
                ('date_end_support', models.DateField()),
                ('date_retired', models.DateField()),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='goNetwork.sede')),
            ],
        ),
    ]
