# Generated by Django 4.1.2 on 2022-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=15)),
                ('business', models.CharField(max_length=15)),
                ('sede', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
