# Generated by Django 4.1.2 on 2022-10-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='business',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sede',
            name='company',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sede',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sede',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sede',
            name='type_sede',
            field=models.CharField(max_length=20),
        ),
    ]
