# Generated by Django 4.1.2 on 2022-10-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_busines_delete_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='busines',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='sede.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='busines',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='busines', to='sede.busines'),
            preserve_default=False,
        ),
    ]
